name: Build Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker Image
        run: |
          docker build -t emx-aarch64-gem5:latest .
      - name: Publish Docker Image
        run: |
          docker tag emx-aarch64-gem5:latest ghcr.io/emmtrix/emx-aarch64-gem5:latest
          docker push ghcr.io/emmtrix/emx-aarch64-gem5:latest
